/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista.GerenteUI;

/**
 *
 * @author Lina
 */
public class PnlGerentePagos extends javax.swing.JPanel {

    /**
     * @return the btnBuscar
     */
    public javax.swing.JButton getBtnBuscar() {
        return btnBuscar;
    }

    /**
     * @param btnBuscar the btnBuscar to set
     */
    public void setBtnBuscar(javax.swing.JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    /**
     * @return the btnEliminar
     */
    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }

    /**
     * @param btnEliminar the btnEliminar to set
     */
    public void setBtnEliminar(javax.swing.JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    /**
     * @return the btnInformacion
     */
    public javax.swing.JButton getBtnInformacion() {
        return btnInformacion;
    }

    /**
     * @param btnInformacion the btnInformacion to set
     */
    public void setBtnInformacion(javax.swing.JButton btnInformacion) {
        this.btnInformacion = btnInformacion;
    }

    /**
     * @return the btnModificar
     */
    public javax.swing.JButton getBtnModificar() {
        return btnModificar;
    }

    /**
     * @param btnModificar the btnModificar to set
     */
    public void setBtnModificar(javax.swing.JButton btnModificar) {
        this.btnModificar = btnModificar;
    }

    /**
     * @return the btnPendientes
     */
    public javax.swing.JButton getBtnPendientes() {
        return btnPendientes;
    }

    /**
     * @param btnPendientes the btnPendientes to set
     */
    public void setBtnPendientes(javax.swing.JButton btnPendientes) {
        this.btnPendientes = btnPendientes;
    }

    /**
     * @return the btnRealizar
     */
    public javax.swing.JButton getBtnRealizar() {
        return btnRealizar;
    }

    /**
     * @param btnRealizar the btnRealizar to set
     */
    public void setBtnRealizar(javax.swing.JButton btnRealizar) {
        this.btnRealizar = btnRealizar;
    }

    /**
     * @return the btnReporte
     */
    public javax.swing.JButton getBtnReporte() {
        return btnReporte;
    }

    /**
     * @param btnReporte the btnReporte to set
     */
    public void setBtnReporte(javax.swing.JButton btnReporte) {
        this.btnReporte = btnReporte;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the tblPagos
     */
    public javax.swing.JTable getTblPagos() {
        return tblPagos;
    }

    /**
     * @param tblPagos the tblPagos to set
     */
    public void setTblPagos(javax.swing.JTable tblPagos) {
        this.tblPagos = tblPagos;
    }

    /**
     * @return the txtBuscar
     */
    public javax.swing.JTextField getTxtBuscar() {
        return txtBuscar;
    }

    /**
     * @param txtBuscar the txtBuscar to set
     */
    public void setTxtBuscar(javax.swing.JTextField txtBuscar) {
        this.txtBuscar = txtBuscar;
    }

    /** Creates new form PnlBodegueroProductos */
    public PnlGerentePagos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInformacion = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnRealizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnPendientes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInformacion.setBackground(new java.awt.Color(77, 98, 94));
        btnInformacion.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnInformacion.setForeground(new java.awt.Color(255, 255, 255));
        btnInformacion.setText("Informacion");
        btnInformacion.setContentAreaFilled(false);
        btnInformacion.setFocusPainted(false);
        btnInformacion.setOpaque(true);
        add(btnInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 30));

        btnModificar.setBackground(new java.awt.Color(77, 98, 94));
        btnModificar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setContentAreaFilled(false);
        btnModificar.setFocusPainted(false);
        btnModificar.setOpaque(true);
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 100, 30));

        btnReporte.setBackground(new java.awt.Color(77, 98, 94));
        btnReporte.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setText("Reporte");
        btnReporte.setContentAreaFilled(false);
        btnReporte.setFocusPainted(false);
        btnReporte.setOpaque(true);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 140, 30));

        txtBuscar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 280, 30));

        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Contrato", "Fecha", "Pago"
            }
        ));
        jScrollPane1.setViewportView(tblPagos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 560, 330));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Search_26px_3.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setFocusPainted(false);
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Search_26px_5.png"))); // NOI18N
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 40, 30));

        btnRealizar.setBackground(new java.awt.Color(77, 98, 94));
        btnRealizar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnRealizar.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizar.setText("Realizar");
        btnRealizar.setContentAreaFilled(false);
        btnRealizar.setFocusPainted(false);
        btnRealizar.setOpaque(true);
        add(btnRealizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 30));

        btnEliminar.setBackground(new java.awt.Color(77, 98, 94));
        btnEliminar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setOpaque(true);
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 100, 30));

        btnPendientes.setBackground(new java.awt.Color(77, 98, 94));
        btnPendientes.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnPendientes.setForeground(new java.awt.Color(255, 255, 255));
        btnPendientes.setText("Pendientes");
        btnPendientes.setContentAreaFilled(false);
        btnPendientes.setFocusPainted(false);
        btnPendientes.setOpaque(true);
        add(btnPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPendientes;
    private javax.swing.JButton btnRealizar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPagos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
