/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class PnlLogin extends javax.swing.JPanel {

    /**
     * Creates new form pnlLogin
     */
    public PnlLogin() {
        initComponents();
    }
    
    public JButton getBtnEntrar(){
        return btnEntrar; 
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public JPasswordField getTxtPass() {
        return txtPass;
    }
    
    //Todos estos geter de los botones solo son para pruebas 

    public JButton getBtnBodeguero() {
        return btnBodeguero;
    }

    public JButton getBtnCajero() {
        return btnCajero;
    }

    public JButton getBtnCocinero() {
        return btnCocinero;
    }

    public JButton getBtnGerente() {
        return btnGerente;
    }

    public JButton getBtnMesero() {
        return btnMesero;
    }

    public JButton getBtnRecepcionista() {
        return btnRecepcionista;
    }

    public JButton getBtnRepartidor() {
        return btnRepartidor;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnRepartidor = new javax.swing.JButton();
        btnBodeguero = new javax.swing.JButton();
        btnCajero = new javax.swing.JButton();
        btnCocinero = new javax.swing.JButton();
        btnGerente = new javax.swing.JButton();
        btnMesero = new javax.swing.JButton();
        btnRecepcionista = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 181, 55));
        setMinimumSize(new java.awt.Dimension(200, 410));
        setPreferredSize(new java.awt.Dimension(200, 410));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Contraseña:");

        btnEntrar.setBackground(new java.awt.Color(77, 98, 94));
        btnEntrar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setContentAreaFilled(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setFocusPainted(false);
        btnEntrar.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>INICIO SESION </html>");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Cedula:");

        txtCedula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        txtPass.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setOpaque(true);

        btnRepartidor.setBackground(new java.awt.Color(77, 98, 94));
        btnRepartidor.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnRepartidor.setForeground(new java.awt.Color(255, 255, 255));
        btnRepartidor.setText("Repartidor");
        btnRepartidor.setContentAreaFilled(false);
        btnRepartidor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepartidor.setFocusPainted(false);
        btnRepartidor.setOpaque(true);

        btnBodeguero.setBackground(new java.awt.Color(77, 98, 94));
        btnBodeguero.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnBodeguero.setForeground(new java.awt.Color(255, 255, 255));
        btnBodeguero.setText("Bodeguero");
        btnBodeguero.setContentAreaFilled(false);
        btnBodeguero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBodeguero.setFocusPainted(false);
        btnBodeguero.setOpaque(true);

        btnCajero.setBackground(new java.awt.Color(77, 98, 94));
        btnCajero.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnCajero.setForeground(new java.awt.Color(255, 255, 255));
        btnCajero.setText("Cajero");
        btnCajero.setContentAreaFilled(false);
        btnCajero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCajero.setFocusPainted(false);
        btnCajero.setOpaque(true);

        btnCocinero.setBackground(new java.awt.Color(77, 98, 94));
        btnCocinero.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnCocinero.setForeground(new java.awt.Color(255, 255, 255));
        btnCocinero.setText("Cocinero");
        btnCocinero.setContentAreaFilled(false);
        btnCocinero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCocinero.setFocusPainted(false);
        btnCocinero.setOpaque(true);

        btnGerente.setBackground(new java.awt.Color(77, 98, 94));
        btnGerente.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnGerente.setForeground(new java.awt.Color(255, 255, 255));
        btnGerente.setText("Gerente");
        btnGerente.setContentAreaFilled(false);
        btnGerente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerente.setFocusPainted(false);
        btnGerente.setOpaque(true);

        btnMesero.setBackground(new java.awt.Color(77, 98, 94));
        btnMesero.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnMesero.setForeground(new java.awt.Color(255, 255, 255));
        btnMesero.setText("Mesero");
        btnMesero.setContentAreaFilled(false);
        btnMesero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesero.setFocusPainted(false);
        btnMesero.setOpaque(true);

        btnRecepcionista.setBackground(new java.awt.Color(77, 98, 94));
        btnRecepcionista.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnRecepcionista.setForeground(new java.awt.Color(255, 255, 255));
        btnRecepcionista.setText("Recepcionista");
        btnRecepcionista.setContentAreaFilled(false);
        btnRecepcionista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecepcionista.setFocusPainted(false);
        btnRecepcionista.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBodeguero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBodeguero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCocinero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btnRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBodeguero;
    private javax.swing.JButton btnCajero;
    private javax.swing.JButton btnCocinero;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnGerente;
    private javax.swing.JButton btnMesero;
    private javax.swing.JButton btnRecepcionista;
    private javax.swing.JButton btnRepartidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
