/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class PnlLogin extends javax.swing.JPanel {

    /**
     * Creates new form pnlLogin
     */
    public PnlLogin() {
        initComponents();
    }
    
    public JButton getBtnEntrar(){
        return btnEntrar; 
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public JPasswordField getTxtPass() {
        return txtPass;
    }
    
    //Todos estos geter de los botones solo son para pruebas 

    public JButton getBtnBodeguero() {
        return btnBodeguero;
    }

    public JButton getBtnCajero() {
        return btnCajero;
    }

    public JButton getBtnCocinero() {
        return btnCocinero;
    }

    public JButton getBtnGerente() {
        return btnGerente;
    }

    public JButton getBtnMesero() {
        return btnMesero;
    }

    public JButton getBtnRecepcionista() {
        return btnRecepcionista;
    }

    public JButton getBtnRepartidor() {
        return btnRepartidor;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnRepartidor = new javax.swing.JButton();
        btnBodeguero = new javax.swing.JButton();
        btnCajero = new javax.swing.JButton();
        btnCocinero = new javax.swing.JButton();
        btnGerente = new javax.swing.JButton();
        btnMesero = new javax.swing.JButton();
        btnRecepcionista = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 181, 55));
        setMinimumSize(new java.awt.Dimension(200, 410));
        setPreferredSize(new java.awt.Dimension(200, 410));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Contraseña:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 170, 30));

        btnEntrar.setBackground(new java.awt.Color(77, 98, 94));
        btnEntrar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setContentAreaFilled(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setFocusPainted(false);
        btnEntrar.setOpaque(true);
        add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 80, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 22)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>INISIO SESION </html>");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 20));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Cedula:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 30));

        txtCedula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 30));

        txtPass.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, 30));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, 5));

        btnRepartidor.setBackground(new java.awt.Color(77, 98, 94));
        btnRepartidor.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnRepartidor.setForeground(new java.awt.Color(255, 255, 255));
        btnRepartidor.setText("Repartidor");
        btnRepartidor.setContentAreaFilled(false);
        btnRepartidor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRepartidor.setFocusPainted(false);
        btnRepartidor.setOpaque(true);
        add(btnRepartidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 20));

        btnBodeguero.setBackground(new java.awt.Color(77, 98, 94));
        btnBodeguero.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnBodeguero.setForeground(new java.awt.Color(255, 255, 255));
        btnBodeguero.setText("Bodeguero");
        btnBodeguero.setContentAreaFilled(false);
        btnBodeguero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBodeguero.setFocusPainted(false);
        btnBodeguero.setOpaque(true);
        add(btnBodeguero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 20));

        btnCajero.setBackground(new java.awt.Color(77, 98, 94));
        btnCajero.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnCajero.setForeground(new java.awt.Color(255, 255, 255));
        btnCajero.setText("Cajero");
        btnCajero.setContentAreaFilled(false);
        btnCajero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCajero.setFocusPainted(false);
        btnCajero.setOpaque(true);
        add(btnCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 20));

        btnCocinero.setBackground(new java.awt.Color(77, 98, 94));
        btnCocinero.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnCocinero.setForeground(new java.awt.Color(255, 255, 255));
        btnCocinero.setText("Cocinero");
        btnCocinero.setContentAreaFilled(false);
        btnCocinero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCocinero.setFocusPainted(false);
        btnCocinero.setOpaque(true);
        add(btnCocinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 20));

        btnGerente.setBackground(new java.awt.Color(77, 98, 94));
        btnGerente.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnGerente.setForeground(new java.awt.Color(255, 255, 255));
        btnGerente.setText("Gerente");
        btnGerente.setContentAreaFilled(false);
        btnGerente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerente.setFocusPainted(false);
        btnGerente.setOpaque(true);
        add(btnGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 90, 20));

        btnMesero.setBackground(new java.awt.Color(77, 98, 94));
        btnMesero.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnMesero.setForeground(new java.awt.Color(255, 255, 255));
        btnMesero.setText("Mesero");
        btnMesero.setContentAreaFilled(false);
        btnMesero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesero.setFocusPainted(false);
        btnMesero.setOpaque(true);
        add(btnMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, 20));

        btnRecepcionista.setBackground(new java.awt.Color(77, 98, 94));
        btnRecepcionista.setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        btnRecepcionista.setForeground(new java.awt.Color(255, 255, 255));
        btnRecepcionista.setText("Recepcionista");
        btnRecepcionista.setContentAreaFilled(false);
        btnRecepcionista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecepcionista.setFocusPainted(false);
        btnRecepcionista.setOpaque(true);
        add(btnRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 110, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBodeguero;
    private javax.swing.JButton btnCajero;
    private javax.swing.JButton btnCocinero;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnGerente;
    private javax.swing.JButton btnMesero;
    private javax.swing.JButton btnRecepcionista;
    private javax.swing.JButton btnRepartidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
